namespace JobAlign.Core.Abstractions;

/// <summary>
/// Outbound email. Currently used only for the password reset link (FR-05).
/// </summary>
/// <remarks>
/// Deliberately minimal and provider-agnostic. FR-05 requires a "verified email
/// link"; the link itself is generated by Identity's token provider, so all this
/// abstraction has to do is deliver it.
/// </remarks>
public interface IAppEmailSender
{
    Task SendAsync(string toEmail, string subject, string body, CancellationToken cancellationToken = default);
}
